# Generated by Django 6.0.7 on 2026-08-21 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('vendors', '0001_initial_vendor_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, help_text='Unique facility code (e.g. WH-ADDIS-BOLE-01)', max_length=50, unique=True)),
                ('city', models.CharField(default='Addis Ababa', max_length=100)),
                ('subcity', models.CharField(blank=True, help_text='e.g., Bole, Kirkos, Yeka', max_length=100)),
                ('wereda', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude for automated distance dispatch calculation', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude for automated distance dispatch calculation', max_digits=9, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Primary hub where single-branch merchants fulfill goods from.')),
                ('is_pickup_point', models.BooleanField(default=False, help_text='True if customers can select this location for Click & Collect pickup.')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorStaffMember',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('STORE_ADMIN', 'Store / Organization Administrator'), ('HUB_MANAGER', 'Warehouse / Hub Branch Manager'), ('INVENTORY_CLERK', 'Inventory Clerk / Stock Counter'), ('DISPATCHER', 'Fulfillment & Pack/Ship Dispatcher'), ('FINANCE_VIEWER', 'Read-Only Financial Auditor')], default='DISPATCHER', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_assignments', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='vendors.vendorprofile')),
                ('assigned_warehouse', models.ForeignKey(blank=True, help_text='Null gives staff member multi-location permissions across all facilities.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='inventory.warehouselocation')),
            ],
            options={
                'ordering': ['role', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE_RECEIPT', 'Inward Stock Purchase Receipt'), ('ORDER_FULFILLMENT', 'Outward Customer Order Fulfillment'), ('ORDER_CANCELLED_RESTOCK', 'Order Cancellation Restock'), ('MANUAL_ADJUSTMENT', 'Manual Inventory Audit Adjustment'), ('DAMAGED_WRITE_OFF', 'Damaged / Expired Inventory Write-Off'), ('TRANSFER_IN', 'Inter-Warehouse Transfer In'), ('TRANSFER_OUT', 'Inter-Warehouse Transfer Out')], max_length=35)),
                ('quantity_delta', models.IntegerField(help_text='Quantity delta (positive for inward, negative for outward/deduction)')),
                ('balance_after', models.IntegerField(help_text='Snapshot of quantity_on_hand immediately following this movement')),
                ('reference_order_id', models.UUIDField(blank=True, help_text='Linked SubOrder or Order UUID if movement originated from fulfillment', null=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.warehouselocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity_on_hand', models.IntegerField(default=0, help_text='Total physical units currently located inside this facility.')),
                ('quantity_reserved', models.IntegerField(default=0, help_text='Units held temporarily during active checkouts or unfulfilled orders.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Threshold triggering low-stock alerts to warehouse managers.')),
                ('aisle_location', models.CharField(blank=True, help_text="Bin / shelf location (e.g. 'Aisle 3, Shelf B-4')", max_length=60)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouselocation')),
            ],
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['vendor', 'is_active'], name='inventory_w_vendor__6c7851_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorstaffmember',
            unique_together={('vendor', 'user')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'variant', '-created_at'], name='inventory_s_warehou_8e9b65_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['warehouse', 'variant'], name='inventory_w_warehou_552373_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousestock',
            index=models.Index(fields=['variant', 'quantity_on_hand'], name='inventory_w_variant_b9d30e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousestock',
            unique_together={('warehouse', 'variant')},
        ),
    ]
