# Generated by Django 6.0.7 on 2026-08-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorStaffMember',
        ),
    ]
