# Generated by Django 6.0.7 on 2026-08-21 15:15

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('vendor_type', models.CharField(choices=[('PLATFORM', 'Platform Direct Store'), ('THIRD_PARTY', 'Third-Party Merchant')], db_index=True, default='THIRD_PARTY', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending KYC Review'), ('APPROVED', 'Approved & Active'), ('REJECTED', 'KYC Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='DRAFT', max_length=20)),
                ('store_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('store_description', models.TextField(blank=True)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/%Y/%m/', validators=[apps.common.validators.validate_image_file])),
                ('store_banner', models.ImageField(blank=True, null=True, upload_to='vendors/banners/%Y/%m/', validators=[apps.common.validators.validate_image_file])),
                ('business_type', models.CharField(choices=[('INDIVIDUAL', 'Individual (ግለሰብ)'), ('SOLE_PROPRIETORSHIP', 'Sole Proprietorship (ግል ድርጅት)'), ('PLC', 'Private Limited Company (PLC)'), ('SHARE_COMPANY', 'Share Company (SC)')], default='INDIVIDUAL', max_length=30)),
                ('tin_number', models.CharField(blank=True, max_length=20, validators=[apps.common.validators.validate_tin_number])),
                ('vat_registered', models.BooleanField(default=False)),
                ('vat_number', models.CharField(blank=True, max_length=30)),
                ('business_license_number', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, validators=[apps.common.validators.validate_ethiopian_phone])),
                ('city', models.CharField(default='Addis Ababa', max_length=100)),
                ('subcity', models.CharField(blank=True, max_length=100)),
                ('wereda', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('tier', models.CharField(choices=[('PROBATION', 'Probation'), ('TRUSTED', 'Trusted'), ('VIP', 'VIP')], db_index=True, default='PROBATION', max_length=20)),
                ('dispute_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Rolling % of orders disputed', max_digits=5)),
                ('cancellation_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Rolling % of orders cancelled by seller', max_digits=5)),
                ('total_completed_orders', models.PositiveIntegerField(default=0, help_text='Cumulative delivered orders')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission % on each order. PLATFORM store = 0.00', max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Mandatory explanation on KYC rejection')),
                ('suspension_reason', models.TextField(blank=True, help_text='Mandatory explanation on store suspension')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBankDetails',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bank_code', models.CharField(db_index=True, help_text="Chapa bank code or 'telebirr'", max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(help_text='Must match business legal name / TIN holder', max_length=150)),
                ('chapa_subaccount_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Bank Details',
                'verbose_name_plural': 'Vendor Bank Details',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('document_type', models.CharField(choices=[('TIN_CERTIFICATE', 'TIN Certificate (የግብር ከፋይ መለያ)'), ('TRADE_LICENSE', 'Renewed Trade License (የታደሰ ንግድ ፈቃድ)'), ('FAYDA_ID', 'Fayda National Digital ID (ፋይዳ)'), ('PASSPORT_OR_KEBELE', 'Passport or Kebele ID'), ('POWER_OF_ATTORNEY', 'Power of Attorney (ውክልና)'), ('OTHER', 'Other Supporting Document')], max_length=30)),
                ('file', models.FileField(upload_to='vendors/kyc/%Y/%m/', validators=[apps.common.validators.validate_document_file])),
                ('document_number', models.CharField(blank=True, help_text='Certificate or registration number', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Set True by admin during KYC approval')),
                ('notes', models.TextField(blank=True, help_text='Admin reviewer notes on this specific document')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Cleared funds ready for payout withdrawal', max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Locked in 72-hour dispute cooldown window', max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, help_text='Cumulative lifetime payouts (append-only via ledger)', max_digits=12)),
                ('is_payout_locked', models.BooleanField(default=False, help_text='Frozen during active disputes or account suspension')),
                ('lock_reason', models.CharField(blank=True, max_length=255)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Wallet',
                'verbose_name_plural': 'Vendor Wallets',
            },
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['status', 'vendor_type'], name='vendors_ven_status_ee0b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['tier', 'status'], name='vendors_ven_tier_dc735f_idx'),
        ),
    ]
