# Generated by Django 6.0.7 on 2026-08-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('vendors', '0001_initial_vendor_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, help_text='Primary root categories the seller is approved to list products in.', related_name='vendors', to='catalog.category'),
        ),
    ]
