# Generated by Django 6.0.7 on 2026-08-24 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_vendorstaffmember'),
        ('vendors', '0002_vendorprofile_allowed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Store Owner'), ('MANAGER', 'Store Operations Manager'), ('INVENTORY_CLERK', 'Inventory Clerk'), ('FULFILLMENT_CLERK', 'Order Fulfillment / Packing'), ('SUPPORT', 'Customer Support Agent')], default='INVENTORY_CLERK', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='inventory.warehouselocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_staff_roles', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='vendors.vendorprofile')),
            ],
            options={
                'unique_together': {('vendor', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VendorStaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('OWNER', 'Store Owner'), ('MANAGER', 'Store Operations Manager'), ('INVENTORY_CLERK', 'Inventory Clerk'), ('FULFILLMENT_CLERK', 'Order Fulfillment / Packing'), ('SUPPORT', 'Customer Support Agent')], default='INVENTORY_CLERK', max_length=32)),
                ('token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouselocation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='vendors.vendorprofile')),
            ],
            options={
                'unique_together': {('vendor', 'email')},
            },
        ),
    ]
