# Generated by Django 6.0.7 on 2026-08-24 06:32

from django.db import migrations


def create_owner_staff_records(apps, schema_editor):
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    VendorStaff = apps.get_model('vendors', 'VendorStaff')
    
    # Using 'OWNER' literal instead of TextChoices because we are in a migration
    for vendor in VendorProfile.objects.all():
        VendorStaff.objects.get_or_create(
            vendor=vendor,
            user=vendor.user,
            defaults={
                'role': 'OWNER',
                'assigned_facility': None,
                'is_active': True,
            }
        )

def reverse_create_owner_staff_records(apps, schema_editor):
    VendorStaff = apps.get_model('vendors', 'VendorStaff')
    VendorStaff.objects.filter(role='OWNER').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorstaff_vendorstaffinvitation'),
    ]

    operations = [
        migrations.RunPython(create_owner_staff_records, reverse_create_owner_staff_records),
    ]
