# Generated by Django 5.1.4 on 2026-08-28 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sprint1_escrow_lifecycle'),
        ('vendors', '0004_auto_20260824_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLedgerEntry',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('entry_type', models.CharField(choices=[('ESCROW_CREDIT', 'Escrow Credit (Pending — awaiting delivery clearance)'), ('ESCROW_RELEASE', 'Escrow Released to Available Balance'), ('ESCROW_REFUND', 'Escrow Refunded (Dispute resolved for buyer)'), ('WITHDRAWAL', 'Payout Withdrawal to Bank / Telebirr')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross sub-order amount before commission deduction.', max_digits=12)),
                ('commission_deducted', models.DecimalField(decimal_places=2, default=0, help_text='Platform commission taken from this entry.', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount credited/debited to the seller (amount - commission_deducted).', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('sub_order', models.ForeignKey(blank=True, help_text='Sub-order this ledger entry relates to, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_ledger_entries', to='orders.vendorsuborder')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='vendors.vendorwallet')),
            ],
            options={
                'verbose_name': 'Vendor Ledger Entry',
                'verbose_name_plural': 'Vendor Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='vendors_ven_wallet__a83c1a_idx'), models.Index(fields=['entry_type', '-created_at'], name='vendors_ven_entry_t_1c96c5_idx')],
            },
        ),
    ]
