# Generated by Django 5.1.4 on 2026-08-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_sprint1_escrow_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorledgerentry',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Effective commission percentage applied (e.g. 10.00%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendorledgerentry',
            name='is_vat_registered_vendor',
            field=models.BooleanField(default=False, help_text='Snapshot of vendor VAT registration status at transaction time.'),
        ),
        migrations.AddField(
            model_name='vendorledgerentry',
            name='platform_net_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform net service revenue before 15% VAT extraction (e.g. 434.78 on 500 ETB commission).', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorledgerentry',
            name='platform_vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='15% VAT extracted from platform commission for MoR/ERCA audit liability (e.g. 65.22 ETB).', max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorledgerentry',
            name='seller_vat_advisory',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Estimated 15% product VAT advisory for VAT-registered seller's own tax filing.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('TIN_CERTIFICATE', 'TIN Certificate (የግብር ከፋይ መለያ)'), ('VAT_CERTIFICATE', 'VAT Registration Certificate (የቫት ምዝገባ ሰርተፊኬት)'), ('TRADE_LICENSE', 'Renewed Trade License (የታደሰ ንግድ ፈቃድ)'), ('FAYDA_ID', 'Fayda National Digital ID (ፋይዳ)'), ('PASSPORT_OR_KEBELE', 'Passport or Kebele ID'), ('POWER_OF_ATTORNEY', 'Power of Attorney (ውክልና)'), ('OTHER', 'Other Supporting Document')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vendorledgerentry',
            name='commission_deducted',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform commission (gross / tax-inclusive) taken from this entry.', max_digits=12),
        ),
    ]
