# Generated by Django 5.1.4 on 2026-08-31 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendorledgerentry_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorwallet',
            name='locked_payout_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Held during in-flight Chapa transfer disbursement (Two-Phase Payout hold)', max_digits=12),
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Gross withdrawal amount requested by seller (e.g. 5,000.00 ETB).', max_digits=12)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=15.0, help_text='Flat Chapa bank transfer fee deducted (15.00 ETB).', max_digits=10)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, help_text='Net amount transferred to seller bank/Telebirr (requested_amount - transfer_fee).', max_digits=12)),
                ('bank_code', models.CharField(help_text="Chapa bank code (e.g. '85' for Dashen, 'telebirr', etc.)", max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=150)),
                ('transfer_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('chapa_response_raw', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Hold on Wallet Balance)'), ('PROCESSING', 'Processing (Dispatched to Chapa Transfer API)'), ('COMPLETED', 'Completed (Settled to Recipient Bank/Telebirr)'), ('FAILED', 'Failed (Rejected by Bank/Chapa, Re-credited)'), ('REJECTED', 'Rejected (Immediate API validation failure)')], db_index=True, default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status', '-created_at'], name='vendors_pay_vendor__b9066f_idx'), models.Index(fields=['status', '-created_at'], name='vendors_pay_status_32f61a_idx')],
            },
        ),
    ]
