# Generated by Django 5.1.4 on 2026-09-01 16:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
        ('orders', '0006_vendorsuborder_is_disputed'),
        ('vendors', '0007_vendorwallet_locked_payout_balance_payoutrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='evidence_image',
        ),
        migrations.AddField(
            model_name='dispute',
            name='customer_notes',
            field=models.TextField(blank=True, default='', help_text='Customer description of the dispute reason.'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='disputed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='dispute',
            name='evidence_images',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded image URLs.'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filed_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('DEFECTIVE', 'Defective / Damaged Item'), ('WRONG_ITEM', 'Wrong Item / Color / Size'), ('COUNTERFEIT', 'Item Not as Described / Counterfeit'), ('MISSING_PARTS', 'Missing Items / Accessories'), ('DAMAGED_TRANSIT', 'Damaged in Transit'), ('OTHER', 'Other')], default='DEFECTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('REFUNDED', 'Refund Approved & Processed'), ('REJECTED', 'Claim Rejected / Escrow Released'), ('CLOSED', 'Closed')], default='UNDER_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='sub_order',
            field=models.OneToOneField(help_text='OneToOne guarantee preventing duplicate dispute claims on the same sub-order.', on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='orders.vendorsuborder'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='vendors.vendorprofile'),
        ),
    ]
