# Generated by Django 6.0.7 on 2026-08-21 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_email', models.EmailField(blank=True, help_text="Snapshot of actor's email address at time of action.", max_length=254)),
                ('actor_role', models.CharField(blank=True, help_text="Snapshot of actor's role/privilege at time of action.", max_length=50)),
                ('action', models.CharField(choices=[('ADMIN_LOGIN', 'Admin Login'), ('STAFF_PROVISIONED', 'Staff Provisioned'), ('STAFF_DEACTIVATED', 'Staff Deactivated'), ('PASSWORD_RESET', 'Password Reset'), ('SELLER_REGISTERED', 'Seller Registered'), ('SELLER_APPROVED', 'Seller Approved'), ('SELLER_SUSPENDED', 'Seller Suspended'), ('SELLER_PROMOTED', 'Seller Promoted'), ('SELLER_DEMOTED', 'Seller Demoted'), ('PRODUCT_APPROVED', 'Product Approved'), ('PRODUCT_REJECTED', 'Product Rejected'), ('PRODUCT_DELETED', 'Product Deleted'), ('COMMISSION_RATE_CHANGED', 'Commission Rate Changed'), ('PLATFORM_SETTING_CHANGED', 'Platform Setting Changed'), ('MAINTENANCE_MODE_TOGGLED', 'Maintenance Mode Toggled'), ('ESCROW_RELEASED', 'Escrow Released'), ('ESCROW_FROZEN', 'Escrow Frozen'), ('PAYOUT_AUTHORIZED', 'Payout Authorized'), ('PAYOUT_REJECTED', 'Payout Rejected'), ('REFUND_ISSUED', 'Refund Issued'), ('GENERIC_ACTION', 'Generic Action')], db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, db_index=True, help_text='Name of the affected entity model (e.g., VendorProfile, Product, PlatformSetting).', max_length=100)),
                ('target_id', models.CharField(blank=True, db_index=True, help_text='Identifier of the target entity.', max_length=100)),
                ('target_repr', models.CharField(blank=True, help_text='Human readable representation of the target entity.', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='JSON capturing before/after states, error messages, or context metadata.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('response_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
