# Generated by Django 6.0.7 on 2026-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ADMIN_LOGIN', 'Admin Login'), ('STAFF_PROVISIONED', 'Staff Provisioned'), ('STAFF_DEACTIVATED', 'Staff Deactivated'), ('PASSWORD_RESET', 'Password Reset'), ('SELLER_REGISTERED', 'Seller Registered'), ('SELLER_APPROVED', 'Seller Approved'), ('SELLER_SUSPENDED', 'Seller Suspended'), ('SELLER_PROMOTED', 'Seller Promoted'), ('SELLER_DEMOTED', 'Seller Demoted'), ('VENDOR_KYC_SUBMITTED', 'Vendor KYC Submitted'), ('VENDOR_KYC_APPROVED', 'Vendor KYC Approved'), ('VENDOR_KYC_REJECTED', 'Vendor KYC Rejected'), ('VENDOR_SUSPENDED', 'Vendor Suspended'), ('VENDOR_REACTIVATED', 'Vendor Reactivated'), ('VENDOR_COMMISSION_UPDATED', 'Vendor Commission Updated'), ('VENDOR_CHAPA_PROVISIONED', 'Vendor Chapa Subaccount Provisioned'), ('PRODUCT_APPROVED', 'Product Approved'), ('PRODUCT_REJECTED', 'Product Rejected'), ('PRODUCT_DELETED', 'Product Deleted'), ('COMMISSION_RATE_CHANGED', 'Commission Rate Changed'), ('PLATFORM_SETTING_CHANGED', 'Platform Setting Changed'), ('MAINTENANCE_MODE_TOGGLED', 'Maintenance Mode Toggled'), ('ESCROW_RELEASED', 'Escrow Released'), ('ESCROW_FROZEN', 'Escrow Frozen'), ('PAYOUT_AUTHORIZED', 'Payout Authorized'), ('PAYOUT_REJECTED', 'Payout Rejected'), ('REFUND_ISSUED', 'Refund Issued'), ('GENERIC_ACTION', 'Generic Action')], db_index=True, max_length=100),
        ),
    ]
