# Generated by Django 5.1.4 on 2026-08-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsuborder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when delivery was confirmed by seller/customer.', null=True),
        ),
        migrations.AddField(
            model_name='vendorsuborder',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when seller marked this sub-order as dispatched.', null=True),
        ),
        migrations.AddField(
            model_name='vendorsuborder',
            name='is_payout_settled',
            field=models.BooleanField(default=False, help_text='True once Celery has released escrow to available_balance.'),
        ),
    ]
