# Generated by Django 5.1.4 on 2026-08-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_shipping_fee_vendorsuborder_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Chapa tx_ref or payment reference', max_length=100),
        ),
    ]
