# Generated by Django 5.1.4 on 2026-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsuborder',
            name='is_disputed',
            field=models.BooleanField(default=False, help_text='True while an active dispute is open.'),
        ),
    ]
