# Generated by Django 5.1.4 on 2026-08-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Root or branch categories where this brand is applicable.', related_name='brands', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic key-value pairs for unlisted or custom attributes.'),
        ),
    ]
