# Generated by Django 5.1.4 on 2026-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_categories_product_custom_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_am',
            field=models.CharField(blank=True, default='', help_text='Amharic translation', max_length=120),
        ),
    ]
