# Generated by Django 6.0.7 on 2026-08-29 09:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_avg_rating_product_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=1, default=Decimal('15.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_class',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('HEAVY', 'Heavy'), ('BULKY', 'Bulky'), ('FRAGILE', 'Fragile'), ('DIGITAL', 'Digital')], db_index=True, default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=1, default=Decimal('10.0'), max_digits=6),
        ),
    ]
