# Generated by Django 6.0.7 on 2026-08-30 06:09

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_height_cm_product_length_cm_and_more'),
        ('vendors', '0005_sprint1_escrow_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStoreCollection',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='vendors/collections/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_attribute_values', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_brands', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_category',
            field=models.CharField(blank=True, help_text='Seller proposed subcategory if leaf is missing.', max_length=150),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(models.F('attribute'), django.db.models.functions.text.Lower('value'), condition=models.Q(('vendor__isnull', True)), name='unique_global_attr_val_lower'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(models.F('attribute'), django.db.models.functions.text.Lower('value'), models.F('vendor'), condition=models.Q(('vendor__isnull', False)), name='unique_vendor_attr_val_lower'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('vendor__isnull', True)), name='unique_global_brand_lower'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('vendor'), condition=models.Q(('vendor__isnull', False)), name='unique_vendor_brand_lower'),
        ),
        migrations.AddField(
            model_name='vendorstorecollection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='store_collections', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='vendorstorecollection',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_collections', to='vendors.vendorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorstorecollection',
            unique_together={('vendor', 'slug')},
        ),
    ]
