# Generated by Django 6.0.7 on 2026-08-30 06:09

from django.db import migrations

def set_existing_brands_attributes_to_global(apps, schema_editor):
    Brand = apps.get_model('catalog', 'Brand')
    AttributeValue = apps.get_model('catalog', 'AttributeValue')
    Brand.objects.filter(is_global=False, vendor__isnull=True).update(is_global=True)
    AttributeValue.objects.filter(is_global=False, vendor__isnull=True).update(is_global=True)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_vendorstorecollection_and_more'),
    ]

    operations = [
        migrations.RunPython(set_existing_brands_attributes_to_global, reverse_code=migrations.RunPython.noop),
    ]
