# Generated by Django 6.0.7 on 2026-08-31 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20260830_0909'),
        ('vendors', '0005_sprint1_escrow_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditAlert',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('alert_type', models.CharField(choices=[('PRICE_SURGE', 'Price Surge'), ('MAJOR_CONTENT_EDIT', 'Major Content Edit'), ('PROBATION_SUBMISSION', 'Probation Submission')], max_length=50)),
                ('diff_payload', models.JSONField(help_text='Detailed JSON showing old vs new values')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_alerts', to='catalog.product')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_audit_alerts', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_alerts', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', 'alert_type'], name='catalog_adm_is_reso_ecdebc_idx'), models.Index(fields=['seller', 'is_resolved'], name='catalog_adm_seller__f465d6_idx')],
            },
        ),
    ]
