# Generated by Django 5.1.4 on 2026-09-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_adminauditalert'),
        ('vendors', '0007_vendorwallet_locked_payout_balance_payoutrequest'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_status_9b3667_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_vendor__bf2425_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-created_at'], name='idx_prod_status_created'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status', '-created_at'], name='idx_prod_cat_stat_created'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'status', '-created_at'], name='idx_prod_vnd_stat_created'),
        ),
    ]
