# Generated by Django 5.1.4 on 2026-08-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_brand_name_am'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='scope_products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='catalog.product'),
        ),
    ]
