# Generated by Django 6.0.7 on 2026-08-29 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingzone',
            name='base_fee',
        ),
        migrations.RemoveField(
            model_name='shippingzone',
            name='estimated_days',
        ),
        migrations.CreateModel(
            name='ShippingZoneRate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shipping_class', models.CharField(choices=[('STANDARD', 'Standard'), ('HEAVY', 'Heavy'), ('BULKY', 'Bulky'), ('FRAGILE', 'Fragile'), ('DIGITAL', 'Digital')], max_length=20)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days_min', models.PositiveSmallIntegerField(default=1)),
                ('estimated_days_max', models.PositiveSmallIntegerField(default=3)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ['zone', 'shipping_class'],
                'unique_together': {('zone', 'shipping_class')},
            },
        ),
    ]
