# Generated by Django 6.0.7 on 2026-08-29 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_remove_shippingzone_base_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneSubCity',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cities', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('zone', 'name')},
            },
        ),
    ]
