# Generated by Django 6.0.7 on 2026-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text='Unique identifier for the setting (e.g., base_commission_rate).', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Serialized string representation of the value.')),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('DECIMAL', 'Decimal'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Operational description of this setting.')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this setting can be safely returned to unauthenticated clients.')),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
                'ordering': ['key'],
            },
        ),
    ]
